# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
version: "3"
services:
  calendar_app:
    container_name: calendar
    restart: always
    build:
      context: ../../..
      dockerfile: docker/containers/exercise/Dockerfile.calendar
    ports:
      - "9090:9090"

  notes_app:
    container_name: notes
    restart: always
    build:
      context: ../../..
      dockerfile: docker/containers/exercise/Dockerfile.notes
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=test_postgres   # References the Postgres container
      - CALENDAR_HOST=calendar  # References the calendar container

  db:
    container_name: test_postgres
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_HOST_AUTH_METHOD: trust 
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5