FROM python:3

WORKDIR /home

COPY requirements.txt /home
COPY notes_app /home/notes_app

RUN pip install -r requirements.txt

# Run the application without the Datadog agent or tracing
CMD ["python", "-m", "notes_app.app"]