version: "3"
services:
  calendar_app:
    container_name: calendar
    restart: always
    build:
      context: ../../..
      dockerfile: docker/containers/exercise/Dockerfile.calendar
    ports:
      - "9090:9090"

  notes_app:
    container_name: notes
    restart: always
    build:
      context: ../../..
      dockerfile: docker/containers/exercise/Dockerfile.notes
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=test_postgres   # References the Postgres container
      - CALENDAR_HOST=calendar  # References the calendar container

  db:
    container_name: test_postgres
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_HOST_AUTH_METHOD: trust 