FROM python:3

WORKDIR /home

COPY requirements.txt /home
COPY /calendar_app /home/calendar_app

RUN pip install -r requirements.txt

# Run the application without the Datadog agent or tracing
CMD ["python", "-m", "calendar_app.app"]