# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
FROM python:3

WORKDIR /home

COPY requirements.txt /home
COPY notes_app /home/notes_app

RUN pip install -r requirements.txt

# Run the application without the Datadog agent or tracing
CMD ["python", "-m", "notes_app.app"]