# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
version: "3"
services:
  db:
    container_name: test_postgres
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      POSTGRES_HOST_AUTH_METHOD: trust 
  notes_app:
    container_name: notes
    restart: always
    build:
      context: ../../..
      dockerfile: docker/host-and-containers/solution/Dockerfile.notes
    ports:
      - "8080:8080"
    depends_on:
      - db
    # extra_hosts:                             # Linux only configuration 
    #   - "host.docker.internal:host-gateway"  # Linux only configuration
    environment:
      - DB_HOST=test_postgres                 # References the Postgres container
      - CALENDAR_HOST=calendar                # References the calendar container
      - DD_AGENT_HOST=host.docker.internal    # Should reference the Agent running on the local machine using docker network
  calendar_app:
    container_name: calendar
    restart: always
    build:
      context: ../../..
      dockerfile: docker/host-and-containers/solution/Dockerfile.calendar
    ports:
      - "9090:9090"
    # extra_hosts:                             # Linux only configuration 
    #   - "host.docker.internal:host-gateway"  # Linux only configuration
    environment:
      - DD_AGENT_HOST=host.docker.internal # Should reference the Agent running on the local machine using docker network