FROM python:3

WORKDIR /home

COPY requirements.txt /home
COPY notes_app /home/notes_app

RUN pip install -r requirements.txt

# Runs the application with Datadog agent and tracing
CMD ["ddtrace-run", "python", "-m", "notes_app.app"]