# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
FROM python:3

WORKDIR /home

COPY requirements.txt /home
COPY calendar_app /home/calendar_app

RUN pip install -r requirements.txt

# Runs the application with Datadog agent and tracing
CMD ["ddtrace-run", "python", "-m", "calendar_app.app"] 